source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, UserDetailView, UserChangeView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    # path('list/', UserListView.as_view(), name='list'),
    path('<int:pk>/update/', UserChangeView.as_view(), name='change'),
    path('<int:pk>/password_change', UserPasswordChangeView.as_view(), name='password_change'),
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from webapp.views import IndexView, ProductView, ProductUpdateView, ProductDeleteView, ProductCreateView, \
    ProductReviewCreateView, ReviewUpdateView, ReviewDeleteView, ReviewModerateUpdateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('product/<int:pk>/', ProductView.as_view(), name='product_view'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('product/<int:pk>/review/add/', ProductReviewCreateView.as_view(), name='product_review_add'),
    path('accounts/', include('accounts.urls')),

    path('review/<int:pk>/moderate/', ReviewModerateUpdateView.as_view(), name='moderate'),
    path('review/<int:pk>/update/', ReviewUpdateView.as_view(), name='review_update'),
    path('review/<int:pk>/delete/', ReviewDeleteView.as_view(), name='review_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from uuid import uuid4
from django.contrib.auth.models import AbstractUser
from django.utils.timezone import now
from datetime import timedelta


class Profile(models.Model):
    user: AbstractUser = models.OneToOneField(get_user_model(), related_name='profile', on_delete=models.CASCADE, verbose_name='Пользователь')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Аватар')
    # link = models.CharField(max_length=200, null=True, blank=True, verbose_name='Ссылка на профиль GitHub')
    # about = models.TextField(max_length=2000, null=True, blank=True, verbose_name='О себе')

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


DEFAULT_CATEGORY = 'other'
CATEGORY_CHOICES = [
    (DEFAULT_CATEGORY, 'Разное'),
    ('food', "Еда"),
    ('toys', 'Игрушки'),
    ('tech', 'Бытовая техника'),
    ('tools', 'Инструменты'),
    ('chemicals', 'Бытовая химия')
]


class Product(models.Model):
    name = models.CharField(max_length=35, null=False, blank=False, verbose_name='Название')
    category = models.CharField(max_length=20, default=DEFAULT_CATEGORY, choices=CATEGORY_CHOICES, verbose_name='Категория')
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name='Описание')
    picture = models.ImageField(null=True, blank=True, upload_to='product_pics', verbose_name='Картинка продукта')

    def __str__(self):
        return f'{self.name} -- {self.category}'

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Review(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='reviews', null=True, verbose_name='Автор')
    product = models.ForeignKey('webapp.Product', related_name='product_reviews', on_delete=models.CASCADE,
                                verbose_name='Продукты')
    text = models.TextField(max_length=2000,  verbose_name='Текст отзыва')
    rating = models.FloatField(verbose_name='Оценка', validators=(MinValueValidator(1),MaxValueValidator(5), ))
    status = models.ForeignKey('webapp.Status', related_name='status', on_delete=models.PROTECT, verbose_name='Статус')

    def __str__(self):
        return f'{self.text} -- {self.author}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural='Отзывы'



class Status(models.Model):
    name = models.CharField(default='Не модерирован', max_length=20, null=False, blank=False, verbose_name='Название статуса')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name='Статус'
        verbose_name_plural='Статусы'

source/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError
from accounts.models import Profile


class MyUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = ['username', 'first_name', 'password1', 'password2', 'email']

    def save(self, commit=True):
        user = super().save(commit=commit)
        Profile.objects.create(user=user)
        return user

    def clean(self):
        cleaned_data = super().clean()
        errors = []
        email = cleaned_data.get('email')
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        if not first_name:
            if not last_name:
                errors.append(ValidationError('You must fill in at least one of the specified fields: last_name, first_name'))
        if not email:
            errors.append(ValidationError('This field is required: email.'))
        if errors:
            raise ValidationError(errors)
        return cleaned_data


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']
        

class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label="Новый пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label="Старый пароль", strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['password', 'password_confirm', 'old_password']

source/accounts/views.py
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView
from django.core.paginator import Paginator
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q, Sum
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache

from accounts.forms import MyUserCreationForm, UserChangeForm, ProfileChangeForm, PasswordChangeForm
from django.views.generic import CreateView, DetailView, ListView, UpdateView

#
# def login_view(request):
#     context = {}
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             login(request, user)
#             return redirect('index')
#         else:
#             context['has_error'] = True
#     return render(request, 'registration/login.html', context=context)
#
#
# def logout_view(request):
#     logout(request)
#     return redirect('index')
from accounts.models import Profile
from webapp.forms import SearchForm


class RegisterView(CreateView):
    model = User
    template_name = 'user_create.html'
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('index')
        return next_url


# class UserListView(PermissionRequiredMixin, ListView):
#     template_name = 'user_list.html'
#     context_object_name = 'users'
#
#     def get_context_data(self, *, object_list=None, **kwargs):
#         form = SearchForm(data=self.request.GET)
#         if form.is_valid():
#             search = form.cleaned_data['search']
#             kwargs['search'] = search
#         kwargs['form'] = form
#         return super().get_context_data(object_list=object_list, **kwargs)
#
#     def get_queryset(self):
#         data = User.objects.all()
#         form = SearchForm(data=self.request.GET)
#         if form.is_valid():
#             search = form.cleaned_data['search']
#             if search:
#                 data = data.filter(Q(name__icontains=search) | Q(description__icontains=search))
#         return data
#
#     def has_permission(self):
#         return self.request.user.groups.filter(pk=2) or self.request.user.groups.filter(pk=3) or self.request.user.pk == 1
#

class UserDetailView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'
    paginate_related_by = 5
    paginate_related_orphans = 0

    # def has_permission(self):
    #     return self.request.user.pk == self.kwargs['pk']

    def get_context_data(self, **kwargs):
        # print(self.object.orders.all())
        # print(self.object)
        #     for product in order.products.all():
        #         paginator = Paginator(product, self.paginate_related_by, orphans=self.paginate_related_orphans)
        #         page_number = self.request.GET.get('page', 1)
        #         page = paginator.get_page(page_number)
        #         kwargs['page_obj'] = page
        #         kwargs['products'] = page.object_list
        #         kwargs['is_paginated'] = page.has_other_pages()
        # return super().get_context_data(**kwargs)
        return super().get_context_data(**kwargs)


class UserChangeView(PermissionRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
        return super().get_context_data(**kwargs)

    def has_permission(self):
        return self.request.user.pk == self.kwargs['pk']

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        form.save()
        profile_form.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)
        return self.render_to_response(context)

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return ProfileChangeForm(**form_kwargs)

        # if self.request.method == 'POST':
        #     form = ProfileChangeForm(instance=self.object, data= self.request.POST,
        #                              files=self.request.FILES)
        # else:
        #     form = ProfileChangeForm(instance=self.object)
        # return form


class UserPasswordChangeView(PermissionRequiredMixin, UpdateView):
    model = get_user_model()
    template_name = 'user_password_change.html'
    form_class = PasswordChangeForm
    context_object_name = 'user_obj'

    def has_permission(self):
        return self.request.user.pk == self.kwargs['pk']

    def get_success_url(self):
        return reverse('accounts:login')

source/accounts/templates/user_change.html
{% extends 'base.html' %}

{% block title %}Редактировать пользователя{% endblock %}

{% block menu %}
    <li><a href="{% url "accounts:detail" user_obj.pk %}">Назад</a></li>
    <li><a href="{% url 'accounts:password_change' user_obj.pk %}">Смена пароля</a></li>
{% endblock %}

{% block content %}
    <h1 class="content">Поменять личные данные</h1>
    <form action="{% url 'accounts:change' user_obj.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'partial/form.html' with form=form fields_only=True %}
        {% include 'partial/form.html' with form=profile_form fields_only=True %}
        <br>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

source/accounts/templates/user_create.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}

{% block auth_menu %}
    {% with request.GET.next as next_url %}
        <li><a href="{% url 'accounts:login' %}{% if next_url %}?next={{ next_url }}{% endif %}">Login</a></li>
        <li><a href="{% url 'accounts:create' %}{% if next_url %}?next={{ next_url }}{% endif %}">Sign Up</a></li>
    {% endwith %}
{% endblock %}

{% block content %}
    <h1 class="content">Регистрация</h1>
    {% include 'partial/form.html' with form_method='post' button_text="Зарегистрироваться" %}
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}

{% block title %}Пользователь{% endblock %}

{% block menu %}
    {% if user_obj.pk == request.user.pk  %}
        <li><a href="{% url 'accounts:change' user_obj.pk %}">Редактировать</a></li>
        <li><a href="{% url 'accounts:password_change' user_obj.pk %}">Смена пароля</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <div style="text-align: left">
        <h1>Личная страница пользователя {{ user_obj.get_full_name|default:user_obj.username }}</h1>
        {% if user_obj.profile.avatar %}
            <img class="avatar" src="{{ user_obj.profile.avatar.url }}" width="250" height="250" alt="user picture">
        {% endif %}
        <p>Логин: {{ user_obj.username }}</p>
        <p>Имя: {{ user_obj.first_name }}</p>
        <p>Почта: {{ user_obj.email }}</p>
    </div>
    <h2 class="text-center clear">Отзывы пользователя:</h2>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
    {% for review in user_obj.reviews.all %}
        <div class="box">
            <h3>Автор:
                <a href="{% url 'accounts:detail' review.author_id %}" class="card-link">{{ review.author }}</a>
            </h3>
            <p>Email: {{ review.author.email }}</p>
            <p>Rate: {{ review.rating }}</p>
            <p>Status: {{ review.status }}</p>
            <hr>
            <div class="pre">{{ review.text }}</div>
            {% if perms.webapp.change_review or review.author == request.user %}
                <p><a href="{% url 'review_update' review.pk %}" class="card-link">Update</a></p>
            {% endif %}
            {% if perms.webapp.delete_review or review.author == request.user %}
                <p><a href="{% url 'review_delete' review.pk %}" class="card-link">Delete</a></p>
            {% endif %}
        </div>
    {% empty %}
        <p>Нет отзыва</p>
    {% endfor %}
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}

source/accounts/templates/user_password_change.html
{% extends 'base.html' %}

{% block title %}Смена пароля{% endblock %}

{% block menu %}
    <li><a href="{% url "accounts:detail" user_obj.pk %}">Назад</a></li>
    <li><a href="{% url "accounts:change" user_obj.pk %}">Редактирование личных данных</a></li>
{% endblock %}

{% block content %}
    <div style="margin-top: 20%">
        <h1>Смена пароля</h1>
        {% url "accounts:password_change" user_obj.pk as action_url %}
        {% include 'partial/form.html' with action_url=action_url form_method="post" %}
    </div>
{% endblock %}