source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, UserDetailView, UserChangeView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    # path('list/', UserListView.as_view(), name='list'),
    path('<int:pk>/update/', UserChangeView.as_view(), name='change'),
    path('<int:pk>/password_change', UserPasswordChangeView.as_view(), name='password_change'),
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from webapp.views import IndexView, ProductView, ProductUpdateView, ProductDeleteView, ProductCreateView, \
    ProductReviewCreateView, ReviewUpdateView, ReviewDeleteView, ReviewModerateUpdateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('product/<int:pk>/', ProductView.as_view(), name='product_view'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('product/<int:pk>/review/add/', ProductReviewCreateView.as_view(), name='product_review_add'),
    path('accounts/', include('accounts.urls')),

    path('review/<int:pk>/moderate/', ReviewModerateUpdateView.as_view(), name='moderate'),
    path('review/<int:pk>/update/', ReviewUpdateView.as_view(), name='review_update'),
    path('review/<int:pk>/delete/', ReviewDeleteView.as_view(), name='review_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


DEFAULT_CATEGORY = 'other'
CATEGORY_CHOICES = [
    (DEFAULT_CATEGORY, 'Разное'),
    ('food', "Еда"),
    ('toys', 'Игрушки'),
    ('tech', 'Бытовая техника'),
    ('tools', 'Инструменты'),
    ('chemicals', 'Бытовая химия')
]


class Product(models.Model):
    name = models.CharField(max_length=35, null=False, blank=False, verbose_name='Название')
    category = models.CharField(max_length=20, default=DEFAULT_CATEGORY, choices=CATEGORY_CHOICES, verbose_name='Категория')
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name='Описание')
    picture = models.ImageField(null=True, blank=True, upload_to='product_pics', verbose_name='Картинка продукта')

    def __str__(self):
        return f'{self.name} -- {self.category}'

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Review(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='reviews', null=True, verbose_name='Автор')
    product = models.ForeignKey('webapp.Product', related_name='product_reviews', on_delete=models.CASCADE,
                                verbose_name='Продукты')
    text = models.TextField(max_length=2000,  verbose_name='Текст отзыва')
    rating = models.FloatField(verbose_name='Оценка', validators=(MinValueValidator(1),MaxValueValidator(5), ))
    status = models.ForeignKey('webapp.Status', related_name='status', on_delete=models.PROTECT, verbose_name='Статус')

    def __str__(self):
        return f'{self.text} -- {self.author}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural='Отзывы'



class Status(models.Model):
    name = models.CharField(default='Не модерирован', max_length=20, null=False, blank=False, verbose_name='Название статуса')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name='Статус'
        verbose_name_plural='Статусы'

source/webapp/forms.py
from django import forms
from webapp.models import Product, Review


class SearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label="Найти")


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = []


class ModerReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['status']


class ProductReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        exclude = ['status', 'author' , 'product']

source/webapp/views/base_views.py
from django.db.models import Q
from django.views.generic import ListView as DjangoListView
from webapp.forms import SearchForm


class SearchView(DjangoListView):
    search_form_class = SearchForm
    search_form_field = 'search'
    search_fields = []

    def get(self, request, *args, **kwargs):
        self.search_form = self.get_search_form()
        self.search_value = self.get_search_value(self.search_form)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['search_form'] = self.search_form
        context['search_value'] = self.search_value
        return context

    def get_queryset(self):
        data = super(SearchView, self).get_queryset()
        query = self.get_query(self.search_value)
        data = data.filter(query)
        return data

    def get_search_form(self):
        return self.search_form_class(data=self.request.GET)

    def get_search_value(self, form):
        search_value = None
        if form.is_valid():
            search_value = form.cleaned_data.get(self.search_form_field, None)
        return search_value

    def get_query(self, search_value):
        query = Q()
        if search_value:
            for field in self.search_fields:
                kwargs = {field: search_value}
                query = query | Q(**kwargs)
        return query

source/webapp/views/product_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Avg
from django.db.models.functions import Coalesce
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, UpdateView, DeleteView, CreateView

from webapp.forms import SearchForm, ProductForm
from webapp.models import Product
from webapp.views.base_views import SearchView


class IndexView(SearchView):
    model = Product
    template_name = 'products/index.html'
    ordering = ['category', 'name']
    search_fields = ['name__icontains']
    paginate_by = 5
    context_object_name = 'products'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     self.average = 0
    #     # Article.objects.annotate(annotated=Coalesce(Count("field"), 0))
    #     for product in Product.objects.all():
    #         product.product_reviews
    #         product.product_reviews.all().annotate(average=Coalesce(Avg('rating'),0))
    #     # context['average'] = self.average
    #     return context
    #
    # def get_average(self, product):
    #     reviews = product.product_reviews.all()
    #     self.average = 0
    #     for review in reviews:
    #         self.average += review.rating
    #     self.average /= reviews.count()
    #     # print(average)
    #     return self.average

    def get_queryset(self):
        return super().get_queryset()


class ProductView(DetailView):
    model = Product
    template_name = 'products/product_view.html'
    paginate_comments_by = 3
    paginate_comments_orphans = 0

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        avg = self.get_average(self.object)
        reviews, page, is_paginated = self.paginate_reviews(self.object)
        context['average'] = avg['average']
        context['reviews'] = reviews
        context['page_obj'] = page
        context['is_paginated'] = is_paginated
        return context

    def get_average(self, product):
        avg = product.product_reviews.all().aggregate(average=Avg('rating'))
        if avg['average'] == None :
            avg['average'] = 0
        return avg

    def paginate_reviews(self, product):
        reviews = product.product_reviews.all().order_by('-rating')
        if reviews.count() > 0:
            paginator = Paginator(reviews, self.paginate_comments_by, orphans=self.paginate_comments_orphans)
            page_number = self.request.GET.get('page', 1)
            page = paginator.get_page(page_number)
            is_paginated = paginator.num_pages > 1  # page.has_other_pages()
            return page.object_list, page, is_paginated
        else:
            return reviews, None, False

    def get_queryset(self):
        return super().get_queryset()


class ProductUpdateView(UpdateView):
    template_name = 'products/product_update.html'
    form_class = ProductForm
    model = Product
    context_object_name = 'product'
    permission_required = 'webapp.change_product'

    def has_permission(self):
        return super().has_permission()

    def get_queryset(self):
        return super().get_queryset()

    def get_success_url(self):
        return reverse('product_view', kwargs={'pk': self.object.pk})


class ProductDeleteView(DeleteView):
    template_name = 'products/product_delete.html'
    model = Product
    success_url = reverse_lazy('index')
    permission_required = 'webapp.delete_product'

    def has_permission(self):
        return super().has_permission()

    def get_queryset(self):
        return super().get_queryset()


class ProductCreateView(CreateView):
    template_name = 'products/product_create.html'
    form_class = ProductForm
    model = Product
    permission_required = 'webapp.add_product'

    def has_permission(self):
        return super().has_permission()

    def get_success_url(self):
        return reverse('product_view', kwargs={'pk': self.object.pk})

source/webapp/views/review_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView

from webapp.models import Review, Product
from webapp.forms import ProductReviewForm, ModerReviewForm


class ProductReviewCreateView(LoginRequiredMixin, CreateView):
    model = Review
    template_name = 'review/review_create.html'
    form_class = ProductReviewForm

    def form_valid(self, form):
        product = get_object_or_404(Product, pk=self.kwargs.get('pk'))
        review = form.save(commit=False)
        review.product = product
        review.author = self.request.user
        review.save()
        # form.save_m2m()  ## для сохранения связей многие-ко-многим
        return redirect('product_view', pk=product.pk)


class ReviewModerateUpdateView(PermissionRequiredMixin, UpdateView):
    model = Review
    template_name = 'review/review_status_edit.html'
    form_class = ModerReviewForm
    permission_required = 'webapp.change_review'

    def has_permission(self):
        review = self.get_object()
        return super().has_permission() or review.author == self.request.user

    def get_success_url(self):
        return reverse('product_view', kwargs={'pk': self.object.product.pk})


class ReviewUpdateView(PermissionRequiredMixin, UpdateView):
    model = Review
    template_name = 'review/review_update.html'
    form_class = ProductReviewForm
    permission_required = 'webapp.change_review'

    def has_permission(self):
        review = self.get_object()
        return super().has_permission() or review.author == self.request.user

    def get_success_url(self):
        return reverse('product_view', kwargs={'pk': self.object.product.pk})


class ReviewDeleteView(PermissionRequiredMixin, DeleteView):
    model = Review
    permission_required = 'webapp.delete_review'

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def has_permission(self):
        review = self.get_object()
        return super().has_permission() or review.author == self.request.user

    def get_success_url(self):
        return reverse('product_view', kwargs={'pk': self.object.product.pk})

source/webapp/templates/products/index.html
{% extends 'base.html' %}
{% block title %}Projects{% endblock %}
{% block styles %}<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">{% endblock %}
{% block search %}
    <div class="search-form">
            <form action="{% url 'index' %}" method="GET">
                <input type="text" name="search">
                <input type="submit" value="Найти">
            </form>
        </div>
{% endblock %}
{% block content %}
<h1>Проекты:</h1>
    {% include 'partial/product_list.html' %}
{% endblock %}

source/webapp/templates/products/product_create.html
{% extends 'base.html' %}

{% block title %}Create{% endblock %}

{% block content %}
    <div class="content">
    <h1>Create Product</h1>
        {% url 'product_create' as action_url %}
        {% include 'partial/form.html' with action_url=action_url form_method='post' enctype="multipart/form-data" %}
    </div>
{% endblock %}

source/webapp/templates/products/product_delete.html
{% extends 'base.html' %}

{% block title %}Delete{% endblock %}

{% block menu %}
    <li><a href="{% url 'product_view' product.pk %}">Отмена</a></li>
{% endblock %}

{% block content %}
    <div class="content">
        <h1>Вы уверены, что хотите удалить продукт "{{ product.name }}"?</h1>
        <p>Категория: {{ product.category }}</p>
        <form action="{% url "product_delete" product.pk %}" method="post" class="delete_buttons">
            {% csrf_token %}
            <button type="submit" class="button accept">Подтвердить</button>
            <a href="{% url 'product_view' product.pk %}" class="button cancel">Отмена</a>
        </form>
        <h3>Содержимое статьи: </h3>
        <p>{{ product.description }}</p>
    </div>
{% endblock %}

source/webapp/templates/products/product_update.html
{% extends "base.html" %}

{% block title %}Update{% endblock %}

{% block menu %}
    <li><a href="{% url 'product_view' product.pk %}">Cancel</a></li>
{% endblock %}

{% block content %}
    <div class="content">
    <h1>Update Product</h1>
        {% url 'product_update' pk=product.pk as action_url %}
        {% include 'partial/form.html' with action_url=action_url form_method='post' enctype="multipart/form-data" %}
    </div>
{% endblock %}

source/webapp/templates/products/product_view.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}View{% endblock %}

{% block menu %}
    {% if perms.webapp.delete_product %}
        <li><a href="{% url 'product_delete' product.pk %}">Delete <i class="fas fa-trash"></i></a></li>
    {% endif %}
    {% if perms.webapp.change_product %}
        <li><a href="{% url 'product_update' product.pk %}">Update <i class="fas fa-edit"></i></a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="product_view">
        {% if product.picture %}
            <img src="{{ product.picture.url }}" class="picture" width="auto" height="250" alt="product picture">
        {% else %}
            <img src="{% static 'img/empty.jpg' %}" width="250" height="250" alt="empty picture">
        {% endif %}
        <h1>{{ product.name }}</h1>
        <p>Категория: {{ product.category }}</p>
        <p>Средняя оценка: {{ average }}</p>
        <label>Описание:</label>
        <p class="pre">{{ product.description }}</p>
        <p><a href="{% url 'product_review_add' product.pk %}" class="card-button">Add review</a></p>
        <h3>Reviews:</h3>
        {% if is_paginated %}
            {% include 'partial/pagination.html' %}
        {% endif %}
        {% for review in reviews %}
        {% if review.status.pk == 1 or perms.webapp.change_review %}
        <div class="box">
            <h3>Автор:
                <a href="{% url 'accounts:detail' review.author_id %}" class="card-link">{{ review.author }}</a>
            </h3>
            <p>Email: {{ review.author.email }}</p>
            <p>Rate: {{ review.rating }}</p>
            <p>Status: {{ review.status }}</p>
            <hr>
            <div class="pre">{{ review.text }}</div>
            {% if perms.webapp.change_product %}
                <p><a href="{% url 'moderate' review.pk %}" class="card-link">Moderate</a></p>
            {% endif %}
            {% if perms.webapp.change_review or review.author == request.user %}
                <p><a href="{% url 'review_update' review.pk %}" class="card-link">Update</a></p>
            {% endif %}
            {% if perms.webapp.delete_review or review.author == request.user %}
                <p><a href="{% url 'review_delete' review.pk %}" class="card-link">Delete</a></p>
            {% endif %}
        </div>
         {% endif %}
        {% empty %}
            <p>Нет отзыва</p>
        {% endfor %}
        {% if is_paginated %}
            {% include 'partial/pagination.html' %}
        {% endif %}
    </div>
{% endblock %}